version: '2'
services:
  server:
    environment:
      - 'PGHOST=postgres'
      - 'PGPORT=5432'
      - 'PORT=3000'
    image: 'bjartur30/tictactoe:${GIT_COMMIT}'
    ports:
      - '80:3000'
      - '8080:8080'
    depends_on:
      - 'postgres'
  postgres:
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=mysecretpassword'
    image: postgres
    ports:
      - "5432:5432"
